"""add voice_template to biometrics

Revision ID: 41e5e7430def
Revises: 00b0a262ac6b
Create Date: 2025-11-30 14:23:12.631307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e5e7430def'
down_revision: Union[str, None] = '00b0a262ac6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biometrics', sa.Column('voice_template', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biometrics', 'voice_template')
    # ### end Alembic commands ###
