"""add pin fields to users

Revision ID: b430e3dcbbf2
Revises: 41e5e7430def
Create Date: 2025-12-14 00:44:34.609214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b430e3dcbbf2'
down_revision: Union[str, None] = '41e5e7430def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_pin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pin_attempts', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('pin_locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_locked_until')
    op.drop_column('users', 'pin_attempts')
    # ### end Alembic commands ###
